### ISSUE TITLE
english word vectors preprocess not working

### ISSUE THREAD

**Issue by mattilyra** [PrekshaNema25/StructuredData_To_Descriptions#1]
In the `data_extraction_scripts/extract_embeddings.sh` file the english word vectors pre processing does not work. There is a filename mismatch `glove.840B.300d.txt` vs. `glove.800B.300d.txt` on lines 16, 17, 18

I'm not exactly sure what the `sed` command is trying to achieve but it looks like it is trying to insert some byte size to each line, is this correct?

**Comment by hrishikeshpatel** [comment]
1. Comment line number 14, 15, 16
2. Manually download glove and rename it to some simple name like "glove.txt"
3. Now put this renamed file into dictionary named "english_embedding".

These steps resolve name mismatch error but it will not help further because English data is not available in the required format.
